var mvUi = angular.module('mvUi', [
  'ngAnimate',
  'ngCookies',
  'ngResource',
  'ngSanitize',
  'ngTouch',
  'ngMessages',
  'mvUi.Config',
  'mvUi.Template',
  'mvUi.Core.Icon',
  'mvUi.Core.IconList',
  'mvUi.Core.IconStack',
  'mvUi.Core.Btn',
  'mvUi.Core.BtnRadio',
  'mvUi.Core.BtnCheckbox',
  'mvUi.Core.BtnModal',
  'mvUi.Layout.Col',
  'mvUi.Layout.Item',
  'mvUi.Layout.List',
  'mvUi.Layout.Row',
  'mvUi.Layout.Container',
  'mvUi.Menu.Dropdown',
  'mvUi.Menu.Paginator',
  'mvUi.Table.Table',
  'mvUi.Window.ModalService',
  'mvUi.Window.Modal',
  'mvUi.Window.ModalHeader',
  'mvUi.Window.ModalBody',
  'mvUi.Window.ModalFooter',
  'mvUi.Form.Form',
  'mvUi.Control', //review
  //'mvUi.Tooltip', //review
  //'mvUi.Progress', // review
  //'mvUi.Switch' //review
]).constant("Modernizr", Modernizr);
